### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by magmax**
simple change to allow python3 compatibility

### CODE REVIEW

**Comment by paetling** [comment]
If you look on line 39 you see `sio = StringIO.StringIO(stat)`.
According to the python [six documentation](https://pythonhosted.org/six/) (and my own experiments) 

```
six.StringIO
This is an fake file object for textual data. It’s an alias for StringIO.StringIO in Python 2 and io.StringIO in Python 3.
```

So you are changing StringIO to mean the class in the module instead of the module it meant before.  Since you are also not changing leaving line 39 the same, this breaks the code. 
We end up with an error similar to the following: 

```
AttributeError: class StringIO has no attribute 'StringIO'
```

**Comment by magmax** [comment]
Previous commit with python3:
`File "/home/miguel/Sandbox/zookeeper_dashboard/zookeeper_dashboard/zkadmin/models.py", line 2, in <module>
    import StringIO
ImportError: No module named 'StringIO'
`

**Comment by paetling** [comment]
I understand why it is breaking in python3.  I am saying that your proposed change does not fix the issue.  It allows you to import, but a new runtime error is introduced, because StringIO no longer references to the module StringIO. Using six, StringIO refers to the class StringIO (from either StringIo or Io).  To fix this, you need to change line 39 from 

```
sio = StringIO.StringIO(stat)
```

to

```
sio = StringIO(stat)
```

**Comment by magmax** [comment]
Sorry, I misunderstood you!

**Comment by paetling** [comment]
Great!  Thanks for the contribution, will merge now.

**Pull request merged**
